CREATE TABLE IF NOT EXISTS `system_article` (
  `id` CHAR(36) NOT NULL DEFAULT (UUID()) PRIMARY KEY COMMENT 'Primary key',
  `is_del` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Soft delete flag',
  `created_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) COMMENT 'Created time',
  `updated_at` DATETIME(6) NULL DEFAULT CURRENT_TIMESTAMP(6) ON UPDATE CURRENT_TIMESTAMP(6) COMMENT 'Updated time',
  `title` VARCHAR(255) NOT NULL COMMENT 'Article title',
  `summary` TEXT NULL COMMENT 'Article summary',
  `cover` VARCHAR(512) NULL COMMENT 'Cover url',
  `content` LONGTEXT NOT NULL COMMENT 'Article content',
  `content_text` LONGTEXT NULL COMMENT 'Plain text content',
  `category_id` VARCHAR(36) NULL COMMENT 'Category id',
  `category_name` VARCHAR(255) NULL COMMENT 'Category name',
  `tag_ids` JSON NULL COMMENT 'Tag ids',
  `tag_names` JSON NULL COMMENT 'Tag names',
  `status` SMALLINT NOT NULL DEFAULT 0 COMMENT '0 draft 1 published',
  `published_at` DATETIME(6) NULL COMMENT 'Published time',
  `author_id` VARCHAR(36) NULL COMMENT 'Author id',
  `author_name` VARCHAR(255) NULL COMMENT 'Author name',
  `sort` INT NOT NULL DEFAULT 0 COMMENT 'Sort value',
  `is_top` TINYINT(1) NOT NULL DEFAULT 0 COMMENT 'Is top',
  `view_count` INT NOT NULL DEFAULT 0 COMMENT 'View count',
  `remark` VARCHAR(500) NULL COMMENT 'Remark',
  INDEX `idx_system_article_status` (`status`),
  INDEX `idx_system_article_category_id` (`category_id`),
  INDEX `idx_system_article_published_at` (`published_at`),
  INDEX `idx_system_article_sort` (`sort`),
  INDEX `idx_system_article_is_top` (`is_top`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='Article table';
